# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task :rust_build do 
  `cargo rustc --release`
  `mv -f target/release/libhello.so ./lib/hello`
end

task :rust_clean do 
  `cargo clean`
  `rm -f ./lib/hello/libhello.so`
end

task :build => :rust_build
task :clean => :rust_clean
task :default => :build
